import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import ParentProvider from '@/components/ParentProvider';
import { ThemeProviderWidget } from '@/components/Theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProviderWidget>
          <ParentProvider>{children}</ParentProvider>
        </ThemeProviderWidget>
      </body>
    </html>
  );
}
