/**
 * This can contain custom Service worker logic use in addition to the
 * autogenerated next-pwa worker logic.
 */

// listen to message event from window
self.addEventListener('message', (event) => {
  // HOW TO TEST THIS?
  // Run this in your browser console:
  //     window.navigator.serviceWorker.controller.postMessage({command: 'clear'})
  // OR use next-pwa injected workbox object
  //     window.workbox.messageSW({command: 'clear'})
  console.log(event?.data);
  if (event?.data.command == 'clear') {
    console.log('clearing caches');
    caches.keys().then(function (names) {
      for (let name of names) caches.delete(name);
    });
  }
});
